
# test-streamlit.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-test
  namespace: hpp
  labels:
    app: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: siriob52/streamlit:latest
        ports:
        - containerPort: 8501
        env:
        - name: API_URL
          value: "http://fastapi-model-service:8000"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  namespace: hpp
spec:
  selector:
    app: streamlit
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: ClusterIP